## Feature aggreagtion and Model prediction

In [1]:
import pandas as pd

In [2]:
acoustic = pd.read_csv("summary_data.csv")
speech = pd.read_csv("summary_sc_data.csv")

acoustic["Participant_ID"] = (
    acoustic["filename"]
    .str.split("_")
    .str[0]
    .astype(int)
)

speech["Participant_ID"] = (
    speech["filename"]
    .str.split("_")
    .str[0]
    .astype(int)
)

In [3]:
print(acoustic[["filename", "Participant_ID"]].head())

    filename  Participant_ID
0  304_AUDIO             304
1  307_AUDIO             307
2  308_AUDIO             308
3  309_AUDIO             309
4  310_AUDIO             310

In [4]:
features = acoustic.merge(
    speech,
    on="Participant_ID",
    suffixes=("_acoustic", "_speech")
)

print(features.shape)

(11, 181)

In [5]:
features

,filename_acoustic,f0_mean,f0_stddev,f0_range,f1_mean,f1_stddev,f1_range,f2_mean,f2_stddev,f2_range,...,turn_to_turn_tangeniality_slope,semantic_perplexity_mean,semantic_perplexity_var,semantic_perplexity_5_mean,semantic_perplexity_5_var,semantic_perplexity_11_mean,semantic_perplexity_11_var,semantic_perplexity_15_mean,semantic_perplexity_15_var,num_interrupts
0,304_AUDIO,207.472289,54.318178,423.842736,668.392502,361.475107,2459.571992,1914.633381,354.623539,3552.477429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,307_AUDIO,207.116232,64.223614,425.022279,589.200504,195.051260,2141.384437,1670.515555,414.610212,3488.286084,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,308_AUDIO,175.368761,62.701366,424.956673,594.839363,219.742938,2320.807609,1559.238502,426.642993,3550.785624,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,309_AUDIO,125.201956,19.432663,400.861384,890.395229,400.723293,2575.166280,2005.254521,455.490543,3879.558812,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,310_AUDIO,93.112803,37.885770,424.239471,941.746765,447.354020,2964.967508,2050.520909,487.337456,3808.713643,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,303_AUDIO,188.906502,43.488919,423.654956,662.581775,382.499636,2780.512772,1861.437412,411.183935,3604.035070,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,300_AUDIO,142.692378,33.985468,400.675842,838.300582,415.131241,2564.684649,2021.737320,406.393246,3670.753560,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,305_AUDIO,131.073994,52.002822,424.756587,537.975002,196.268502,2391.850291,1491.973157,394.811424,3569.962696,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,306_AUDIO,175.739951,51.015060,398.633645,576.900834,211.565695,2376.756616,1626.238283,422.002795,3556.390788,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,302_AUDIO,123.141434,60.568361,421.362666,806.716300,436.613697,2603.444462,2009.477959,388.336850,3634.422778,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,301_AUDIO,109.493225,32.829141,421.643314,720.733265,386.415033,2696.875172,1874.539234,436.320379,3602.792541,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
train = pd.read_csv("data/train_split_Depression_AVEC2017.csv")
dev = pd.read_csv("data/dev_split_Depression_AVEC2017.csv")

labels = pd.concat([train, dev], ignore_index=True)

In [7]:
labels = labels[
    ["Participant_ID", "PHQ8_Score", "PHQ8_Binary"]
]

In [8]:
labels

     Participant_ID  PHQ8_Score  PHQ8_Binary
0               303           0            0
1               304           6            0
2               305           7            0
3               310           4            0
4               312           2            0
..              ...         ...          ...
137             483          15            1
138             484           9            0
139             489           3            0
140             490           2            0
141             492           0            0

[142 rows x 3 columns]

In [13]:
df = features.merge(
    labels,
    on="Participant_ID",
    how="inner"
)

print(df.shape)

(6, 183)

In [14]:
df

,filename_acoustic,f0_mean,f0_stddev,f0_range,f1_mean,f1_stddev,f1_range,f2_mean,f2_stddev,f2_range,...,semantic_perplexity_var,semantic_perplexity_5_mean,semantic_perplexity_5_var,semantic_perplexity_11_mean,semantic_perplexity_11_var,semantic_perplexity_15_mean,semantic_perplexity_15_var,num_interrupts,PHQ8_Score,PHQ8_Binary
0,304_AUDIO,207.472289,54.318178,423.842736,668.392502,361.475107,2459.571992,1914.633381,354.623539,3552.477429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,0
1,307_AUDIO,207.116232,64.223614,425.022279,589.200504,195.051260,2141.384437,1670.515555,414.610212,3488.286084,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0
2,310_AUDIO,93.112803,37.885770,424.239471,941.746765,447.354020,2964.967508,2050.520909,487.337456,3808.713643,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0
3,303_AUDIO,188.906502,43.488919,423.654956,662.581775,382.499636,2780.512772,1861.437412,411.183935,3604.035070,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
4,305_AUDIO,131.073994,52.002822,424.756587,537.975002,196.268502,2391.850291,1491.973157,394.811424,3569.962696,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,0
5,302_AUDIO,123.141434,60.568361,421.362666,806.716300,436.613697,2603.444462,2009.477959,388.336850,3634.422778,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0

In [15]:
df = df.dropna(axis=1, how="all")

In [20]:
df

,filename_acoustic,f0_mean,f0_stddev,f0_range,f1_mean,f1_stddev,f1_range,f2_mean,f2_stddev,f2_range,...,brunet_index,yngve_score,frazier_score,first_person_percentage,first_person_sentiment_positive,first_person_sentiment_negative,first_person_sentiment_overall,word_repeat_percentage,PHQ8_Score,PHQ8_Binary
0,304_AUDIO,207.472289,54.318178,423.842736,668.392502,361.475107,2459.571992,1914.633381,354.623539,3552.477429,...,13.265032,33.750000,69.733333,19.708029,12.766423,0.729197,12.766423,4.945398,6,0
1,307_AUDIO,207.116232,64.223614,425.022279,589.200504,195.051260,2141.384437,1670.515555,414.610212,3488.286084,...,13.639006,56.071429,107.757143,25.110132,15.352423,1.607048,15.352423,4.271127,4,0
2,310_AUDIO,93.112803,37.885770,424.239471,941.746765,447.354020,2964.967508,2050.520909,487.337456,3808.713643,...,12.847888,29.659574,61.276596,19.753086,12.277778,1.679012,12.277778,6.738895,4,0
3,303_AUDIO,188.906502,43.488919,423.654956,662.581775,382.499636,2780.512772,1861.437412,411.183935,3604.035070,...,14.321235,62.596154,142.480769,13.669065,18.302158,0.560432,18.302158,4.997560,0,0
4,305_AUDIO,131.073994,52.002822,424.756587,537.975002,196.268502,2391.850291,1491.973157,394.811424,3569.962696,...,14.079689,41.679245,86.358491,28.472222,10.156944,1.822222,10.156944,6.219161,7,0
5,302_AUDIO,123.141434,60.568361,421.362666,806.716300,436.613697,2603.444462,2009.477959,388.336850,3634.422778,...,11.893540,34.708333,63.875000,22.222222,18.900000,1.022222,18.900000,2.205638,4,0

In [17]:
corr = (
    df.select_dtypes(include="number")
      .corr()["PHQ8_Score"]
      .sort_values(key=abs, ascending=False)
)

print(corr.head(20))

PHQ8_Score                         1.000000
first_person_percentage            0.795670
hnr_range                          0.788869
first_person_sentiment_overall    -0.757419
first_person_sentiment_positive   -0.757419
frazier_score                     -0.685416
cpp_var                           -0.680527
yngve_score                       -0.630422
honore_statistic                   0.620471
cpp_mean                          -0.615176
mfcc3_mean                         0.609218
sentiment_pos                     -0.601646
sentiment_neu                      0.567196
lhr_var                            0.564807
hnr_mean                          -0.558110
first_person_sentiment_negative    0.535539
loudness_range                     0.532597
cpp_kurtosis                       0.521189
gne_ratio                         -0.512508
lhr_mean                           0.488566
Name: PHQ8_Score, dtype: float64

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

X = df.drop(
    columns=["Participant_ID",
             "filename_acoustic",
             "filename_speech",
             "PHQ8_Score",
             "PHQ8_Binary"]
)

y = df["PHQ8_Score"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = RandomForestRegressor(
    n_estimators=300,
    random_state=42
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, pred))

MAE: 1.6066666666666667

In [22]:
importance = pd.DataFrame({
    "feature": X.columns,
    "importance": model.feature_importances_
})

importance = importance.sort_values(
    "importance",
    ascending=False
)

importance.head(20)

                             feature  importance
85                 syllables_per_min    0.036101
60                         mfcc6_var    0.030492
92                 sentiment_overall    0.025927
72                      cpp_skewness    0.025271
10                         f3_stddev    0.022585
62                         mfcc8_var    0.020129
51                       mfcc11_mean    0.019503
99                      brunet_index    0.018737
9                            f3_mean    0.018051
78                              acf1    0.017116
0                            f0_mean    0.016300
36                       f0_kurtosis    0.016051
104  first_person_sentiment_negative    0.016051
18                          hnr_mean    0.016051
102          first_person_percentage    0.016051
73              spectral_variability    0.015316
24                       jitter_ppq5    0.014440
26                           shimmer    0.014440
6                            f2_mean    0.014440
20                         hnr_range    0.014033

In [ ]:
from scipy.stats import pearsonr
import pandas as pd

results = []

for col in X.columns:
    r, p = pearsonr(df[col], df["PHQ8_Score"])

    results.append({
        "feature": col,
        "r": r,
        "p": p
    })

corr_df = pd.DataFrame(results)

In [ ]:
from statsmodels.stats.multitest import multipletests

corr_df["p_fdr"] = multipletests(
    corr_df["p"],
    method="fdr_bh"
)[1]

corr_df = corr_df.sort_values("p_fdr")